apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: takuyak/nginx-sample-bl:TAG
        name: blue
        ports:
          - containerPort: 80
