apiVersion: app/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: tkawavmw/githubtest:513c014c766063079e3b78adb023793fa185b2bd
        name: blue
        ports:
          - containerPort: 80
