apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green
  labels:
    name: app
    app: nginxjs
    color: green
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  template:
    metadata:
      name: green
      labels:
        name: app
        app: nginxjs
        color: green
    spec:
      containers:
      - image: docker.io/takuyak/nginx-sample-gr:latest
        name: green
        ports:
          - containerPort: 80
